baseURL = 'https://seawise.gr'
languageCode = 'en-us'
title = 'SeaWise'
theme = "ananke"

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "SeaWise"
    weight = 1
    contentDir = "content/en"

[params]
  background_color_class = "bg-black"
  body_classes = "avenir bg-light-gray"
